/**
 * ShipTilemap
 * ─────────────────────────────────────────────────────────────────────────────
 * Builds a Phaser Tilemap for the ship interior using the pixel-art tileset
 * generated by TilesetGenerator.
 *
 * Three render layers (depths):
 *   - floor  (depth 2) — zone floors, corridors, hull interior
 *   - walls  (depth 3) — auto-tiled wall blocks with proper face tiles
 *   - detail (depth 4) — overlay detail patterns (edge accents, markings)
 *
 * Zone layout is derived from mapData.ts ZONES so it stays in sync with agent
 * spawn positions.
 */

import Phaser from 'phaser';
import { ZONES, MAP_COLS, MAP_ROWS } from './mapData';
import type { AgentZone } from '@agent-space/shared';
import { T, TILESET_KEY, TILE_SIZE } from './TilesetGenerator';

// ── Cell type enum (internal only) ───────────────────────────────────────────
const C = {
  SPACE:    0,
  HULL:     1,
  CORRIDOR: 2,
  BRIDGE:   3,
  ENGINE:   4,
  HANGAR:   5,
  ALERT:    6,
  WALL:     7,   // wall cell (belongs to a zone boundary)
} as const;
type CellType = typeof C[keyof typeof C];

/** Zone floor tile variants (A/B/C) keyed by cell type. */
const FLOOR_TILES: Record<number, number[]> = {
  [C.BRIDGE]:   [T.BRIDGE_A, T.BRIDGE_B, T.BRIDGE_C],
  [C.ENGINE]:   [T.ENGINE_A, T.ENGINE_B, T.ENGINE_C],
  [C.HANGAR]:   [T.HANGAR_A, T.HANGAR_B, T.HANGAR_C],
  [C.ALERT]:    [T.ALERT_A,  T.ALERT_B,  T.ALERT_C],
  [C.CORRIDOR]: [T.CORRIDOR, T.CORRIDOR, T.CORRIDOR],
  [C.HULL]:     [T.HULL_INT, T.HULL_INT, T.HULL_INT],
  [C.SPACE]:    [T.VOID,     T.SPACE,    T.VOID],
};

export class ShipTilemap {
  constructor(scene: Phaser.Scene) {
    // 1. Build the logical grid
    const grid = buildGrid();

    // 2. Create a blank Phaser tilemap
    const map = scene.make.tilemap({
      width:      MAP_COLS,
      height:     MAP_ROWS,
      tileWidth:  TILE_SIZE,
      tileHeight: TILE_SIZE,
    });

    // 3. Add the generated tileset image
    //    margin=0, spacing=0, tileWidth/Height match tile size
    const tileset = map.addTilesetImage(
      TILESET_KEY,          // key matches TilesetGenerator.KEY
      TILESET_KEY,          // image key (same name registered by addCanvas)
      TILE_SIZE, TILE_SIZE,
      0, 0,
    )!;

    // 4. Create layers
    const floorLayer  = map.createBlankLayer('floor',  tileset, 0, 0)!.setDepth(2);
    const wallLayer   = map.createBlankLayer('walls',  tileset, 0, 0)!.setDepth(3);
    const detailLayer = map.createBlankLayer('detail', tileset, 0, 0)!.setDepth(4);

    // 5. Place tiles
    const rng = seededRng(7);

    for (let row = 0; row < MAP_ROWS; row++) {
      for (let col = 0; col < MAP_COLS; col++) {
        const cell = grid[row][col];

        // ── Floor layer ──────────────────────────────────────────────────
        if (cell !== C.WALL) {
          const variants = FLOOR_TILES[cell] ?? [T.VOID];
          const variant  = variants[Math.floor(rng() * variants.length)];
          floorLayer.putTileAt(variant, col, row);
        }

        // ── Wall layer ───────────────────────────────────────────────────
        if (cell === C.WALL) {
          const wallTile = selectWallTile(grid, col, row);
          wallLayer.putTileAt(wallTile, col, row);

          // Also paint a floor tile beneath the wall (visual depth)
          const adj = adjacentFloorCell(grid, col, row);
          if (adj !== null) {
            const variants = FLOOR_TILES[adj] ?? [T.HULL_INT];
            floorLayer.putTileAt(
              variants[Math.floor(rng() * variants.length)],
              col, row,
            );
          } else {
            floorLayer.putTileAt(T.HULL_INT, col, row);
          }
        }

        // ── Detail layer — zone-specific floor accents ────────────────────
        placeDetail(detailLayer, cell, col, row, rng);
      }
    }

    // 6. Tint wall layer slightly per-zone by scanning adjacency
    applyZoneTints(wallLayer, grid, MAP_COLS, MAP_ROWS);
  }
}

// ═══════════════════════════════════════════════════════════════════════════════
//  GRID BUILDER
// ═══════════════════════════════════════════════════════════════════════════════

function buildGrid(): CellType[][] {
  const grid: CellType[][] = Array.from({ length: MAP_ROWS }, () =>
    Array(MAP_COLS).fill(C.SPACE),
  );

  // Mark hull interior (ship bounding box: cols 6–29, rows 3–27)
  for (let r = 3; r < 28; r++) {
    for (let c = 6; c < 30; c++) {
      grid[r][c] = C.HULL;
    }
  }
  // Left nacelle
  for (let r = 12; r < 22; r++) {
    for (let c = 1; c < 6; c++) grid[r][c] = C.HULL;
  }
  // Right nacelle
  for (let r = 12; r < 22; r++) {
    for (let c = 30; c < 35; c++) grid[r][c] = C.HULL;
  }

  // Paint each zone: outer 1-tile border = WALL, interior = zone type
  const zoneTypes: [AgentZone, CellType][] = [
    ['bridge',      C.BRIDGE],
    ['engine_room', C.ENGINE],
    ['hangar',      C.HANGAR],
    ['alert_bay',   C.ALERT],
  ];

  for (const [name, cellType] of zoneTypes) {
    const z = ZONES[name];
    for (let r = z.y; r < z.y + z.h; r++) {
      for (let c = z.x; c < z.x + z.w; c++) {
        const isWall =
          r === z.y || r === z.y + z.h - 1 ||
          c === z.x || c === z.x + z.w - 1;
        grid[r][c] = isWall ? C.WALL : cellType;
      }
    }
  }

  // Corridors between zones
  // Between bridge bottom and engine/hangar top
  const bridgeBot = ZONES.bridge.y + ZONES.bridge.h;
  const engineTop = ZONES.engine_room.y;
  for (let r = bridgeBot; r < engineTop; r++) {
    for (let c = 6; c < 30; c++) grid[r][c] = C.CORRIDOR;
  }

  // Between engine/hangar bottom and alert top
  const engineBot = ZONES.engine_room.y + ZONES.engine_room.h;
  const alertTop  = ZONES.alert_bay.y;
  for (let r = engineBot; r < alertTop; r++) {
    for (let c = 6; c < 30; c++) grid[r][c] = C.CORRIDOR;
  }

  return grid;
}

// ═══════════════════════════════════════════════════════════════════════════════
//  WALL AUTO-TILING
// ═══════════════════════════════════════════════════════════════════════════════

/** Returns true if the cell at (c,r) is NOT a wall (i.e. has a visible floor). */
function isFloor(grid: CellType[][], c: number, r: number): boolean {
  if (r < 0 || r >= MAP_ROWS || c < 0 || c >= MAP_COLS) return false;
  const cell = grid[r][c];
  return cell !== C.WALL && cell !== C.SPACE && cell !== C.HULL;
}

/**
 * Chooses the correct wall tile based on which cardinal directions have a
 * floor neighbour (i.e. which face of the wall is exposed).
 */
function selectWallTile(grid: CellType[][], c: number, r: number): number {
  const N = isFloor(grid, c, r - 1);
  const S = isFloor(grid, c, r + 1);
  const W = isFloor(grid, c - 1, r);
  const E = isFloor(grid, c + 1, r);

  // Exposed face: only one direction open
  if (S && !N && !W && !E) return T.WALL_N;    // floor below → south-facing wall face visible from north
  if (N && !S && !W && !E) return T.WALL_S;
  if (E && !N && !S && !W) return T.WALL_W;
  if (W && !N && !S && !E) return T.WALL_E;

  // Outer corners (two adjacent floor directions)
  if (S && E && !N && !W) return T.WALL_NW;
  if (S && W && !N && !E) return T.WALL_NE;
  if (N && E && !S && !W) return T.WALL_SW;
  if (N && W && !S && !E) return T.WALL_SE;

  // Inner concave corners
  if (N && W && S && E) return T.WALL_FILL;
  if (N && S && !W && !E) return T.WALL_V;
  if (W && E && !N && !S) return T.WALL_H;

  // Inner corners
  if (N && W && !S && !E) return T.WALL_INW;
  if (N && E && !S && !W) return T.WALL_INE;
  if (S && W && !N && !E) return T.WALL_ISW;
  if (S && E && !N && !W) return T.WALL_ISE;

  return T.WALL_FILL;
}

/** Find the floor cell type adjacent to a wall (for painting floor beneath wall). */
function adjacentFloorCell(grid: CellType[][], c: number, r: number): CellType | null {
  for (const [dc, dr] of [[0,-1],[0,1],[-1,0],[1,0]]) {
    const nc = c + dc, nr = r + dr;
    if (nr >= 0 && nr < MAP_ROWS && nc >= 0 && nc < MAP_COLS) {
      const cell = grid[nr][nc];
      if (cell !== C.WALL && cell !== C.SPACE) return cell;
    }
  }
  return null;
}

// ═══════════════════════════════════════════════════════════════════════════════
//  DETAIL LAYER
// ═══════════════════════════════════════════════════════════════════════════════

function placeDetail(
  layer: Phaser.Tilemaps.TilemapLayer,
  cell: CellType,
  col: number,
  row: number,
  rng: () => number,
) {
  // Hangar: landing stripe pattern on B-variant tiles
  if (cell === C.HANGAR) {
    const z = ZONES.hangar;
    const cx = Math.floor(z.x + z.w / 2);
    const cy = Math.floor(z.y + z.h / 2);
    if (col === cx || col === cx + 1) {
      layer.putTileAt(T.HANGAR_B, col, row);
    }
    if (row === cy || row === cy + 1) {
      layer.putTileAt(T.HANGAR_C, col, row);
    }
  }

  // Alert: alternate stripe directions for checker pattern
  if (cell === C.ALERT) {
    const stripeVariant = (col + row) % 2 === 0 ? T.ALERT_B : T.ALERT_C;
    layer.putTileAt(stripeVariant, col, row);
  }

  // Bridge: occasional B/C variants for visual break
  if (cell === C.BRIDGE && rng() < 0.12) {
    layer.putTileAt(rng() < 0.5 ? T.BRIDGE_B : T.BRIDGE_C, col, row);
  }
}

// ═══════════════════════════════════════════════════════════════════════════════
//  ZONE WALL TINTS
// ═══════════════════════════════════════════════════════════════════════════════

const ZONE_WALL_TINT: [AgentZone, number][] = [
  ['bridge',      0x3366aa],
  ['engine_room', 0xaa4400],
  ['hangar',      0x006644],
  ['alert_bay',   0xaa0022],
];

function applyZoneTints(
  wallLayer: Phaser.Tilemaps.TilemapLayer,
  grid: CellType[][],
  cols: number,
  rows: number,
) {
  const zoneCells: Record<string, CellType> = {
    bridge: C.BRIDGE, engine_room: C.ENGINE, hangar: C.HANGAR, alert_bay: C.ALERT,
  };

  for (const [zoneName, tint] of ZONE_WALL_TINT) {
    const z   = ZONES[zoneName];
    const ct  = zoneCells[zoneName];

    for (let r = z.y; r < z.y + z.h; r++) {
      for (let c = z.x; c < z.x + z.w; c++) {
        if (grid[r][c] === C.WALL) {
          // Check if any neighbour is this zone's floor type
          let adjacentToZone = false;
          for (const [dc, dr] of [[0,-1],[0,1],[-1,0],[1,0]]) {
            const nc = c + dc, nr = r + dr;
            if (nr >= 0 && nr < rows && nc >= 0 && nc < cols) {
              if (grid[nr][nc] === ct) { adjacentToZone = true; break; }
            }
          }
          if (adjacentToZone) {
            const tile = wallLayer.getTileAt(c, r);
            if (tile) tile.tint = tint;
          }
        }
      }
    }
  }
}

// ═══════════════════════════════════════════════════════════════════════════════
//  UTILITIES
// ═══════════════════════════════════════════════════════════════════════════════

/** Simple seeded LCG — same sequence every run → deterministic tile variant layout. */
function seededRng(seed: number): () => number {
  let s = seed;
  return () => {
    s = (s * 1664525 + 1013904223) & 0xffffffff;
    return (s >>> 0) / 0xffffffff;
  };
}
